services:
  app:
    build:
        context: .
    image: car-simulation-app:latest
    container_name: car-simulation-app
    working_dir: /var/www
    volumes:
        - .:/var/www
        - ./storage:/var/www/storage
    ports:
      - '8000:8000'
